-   id: check-config
    name: check ini files
    description: This hook checks ini files for parseable syntax.
    entry: check-config
    language: python
    'types': ['ini']
    args: []
    require_serial: false
    additional_dependencies: []
